ubuntu:
  build: .
  ports:
   - '8080:8080'
  environment:
    CFG_APP_DEBUG: 1
    SERVER_LOG_MINIMAL: 1
    PHP_FPM_MEMORY_LIMIT: 256M
    PHP_FPM_MAX_EXECUTION_TIME: 61
    PHP_FPM_UPLOAD_MAX_FILESIZE: 100M
    SERVER_APP_NAME: docker-test
    REPLACE_NEWRELIC_APP: abcdefg
    REPLACE_NEWRELIC_LICENSE: hijklmno
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
  volumes:
   - ./container/root/app:/app
   - ./container/root/goss.base.yaml:/goss.base.yaml
   - ./container/root/goss.ubuntu.yaml:/goss.ubuntu.yaml
alpine:
  build: .
  dockerfile: Dockerfile-alpine
  ports:
   - '8081:8080'
  environment:
    CFG_APP_DEBUG: 1
    SERVER_LOG_MINIMAL: 1
    PHP_FPM_MEMORY_LIMIT: 256M
    PHP_FPM_MAX_EXECUTION_TIME: 61
    PHP_FPM_UPLOAD_MAX_FILESIZE: 100M
    SERVER_APP_NAME: docker-test
    REPLACE_NEWRELIC_APP: abcdefg
    REPLACE_NEWRELIC_LICENSE: hijklmno
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
  volumes:
   - ./container/root/app:/app
   - ./container/root/goss.base.yaml:/goss.base.yaml
   - ./container/root/goss.alpine.yaml:/goss.alpine.yaml
edge:
  build: .
  dockerfile: Dockerfile-edge
  ports:
   - '8082:8080'
  environment:
    CFG_APP_DEBUG: 1
    SERVER_LOG_MINIMAL: 1
    PHP_FPM_MEMORY_LIMIT: 256M
    PHP_FPM_MAX_EXECUTION_TIME: 61
    PHP_FPM_UPLOAD_MAX_FILESIZE: 100M
    SERVER_APP_NAME: docker-test
    REPLACE_NEWRELIC_APP: abcdefg
    REPLACE_NEWRELIC_LICENSE: hijklmno
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
  volumes:
   - ./container/root/app:/app
   - ./container/root/goss.base.yaml:/goss.base.yaml
   - ./container/root/goss.beta.yaml:/goss.beta.yaml
